### PR TITLE
Fix fasta file generation and change fasta files to use 2bit as source

### PR DESCRIPTION
**Pull request by Xewar313**
https://github.com/JetBrains-Research/bioinf-commons/issues/19

### CODE REVIEW

**Comment by iromeo** [comment]
I see that `fun Iterable<FastaRecord>.write(path: Path, width: Int = 80)` was introduced earlier and wont covered by tests. Could you please cover it with some unit tests. In tests `hg38`, `hg19` and other real genomes are not available. Instead, we use a generated `Genome["to1"]` genome with a couple of chromosomes.
* For this method seems you do not need `to1` and it's ok to generate same fake FastaRecords that are configured using string sequence + validate that header and split by desired width works ok

Also, please add a test for `Genome.writeAsFasta` and verify:
* that the chromosomes order in resulting file is same as in Genome.chromSizesMap
* that chromosomes sequence start with same nucleotieds as in Chromosome.sequence() for correspoding chromosomes 
* chomosome lenth in result file matched to Chromosome length in `to1` genome.
Keep in mind, that exact nucleotide sequence in the test chromosome is randomly generated, although seed is fixed and it should be same each time (see org.jetbrains.bio.genome.TestOrganismDataGenerator#generateSequence)

**Comment by iromeo** [comment]
Also `AnnotationsConfig.fastaUrl` isn't used any more, so seems we could clean it up

**Comment by iromeo** [comment]
@Xewar313 `GenomeAnnotationEditor` compilation is broken due to missing fasta url in epigenome repo, please fix there also

**Comment by Xewar313** [comment]
@iromeo Sorry, I have forgotten to push jbr changes

**Pull request merged**
